### ISSUE TITLE
Program in linux output is not matched with its resources

### ISSUE THREAD

**Issue by matkoniecz** [Kha-Samples/BlocksFromHeaven#5]
I did 

`git clone --recursive https://github.com/Kha-Samples/BlocksFromHeaven.git`

followed by `node Kha/make linux` what produced something that I compiled again.

I used `make` in `BlocksFromHeaven/build/linux-build/Release` what produced I did 

`git clone --recursive https://github.com/Kha-Samples/BlocksFromHeaven.git``BlocksFromHeaven/build/linux-build/Release/Blocks` file.

Sadly, running it flashes small window with an empty background and

```
Initializing Haxe libraries
Starting Kore
Could not open file block_blue.k.
Could not open file block_blue.k.
```

outputs shows in the console.

`find | grep block_blue` found `./build/linux/block_blue.k`

After copying `BlocksFromHeaven/build/linux-build/Release/Blocks` to `BlocksFromHeaven/build/linux` it started to work.

I would expect that it is done as a part of the build.

**Comment by RobDangerous** [comment]
Works as intended. Please use the forum to discuss basic workflows.

**Comment by RobDangerous** [comment]
For all kinds of questions please also use the forum. Please please stop using GitHub issues for everything but reporting issues.
